version: '3'
services:
  api:
    build:
      context: .
    volumes:
      - ./main.go:/go/src/github.com/rdegges/ipify-api/main.go
      - ./api:/go/src/github.com/rdegges/ipify-api/api
      - ./models:/go/src/github.com/rdegges/ipify-api/models
    environment:
      - PORT=9091
    ports:
      - "9091:9091"
